version: '3.8'

services:
  server:
    build:
      context: ./server
      dockerfile: Dockerfile
    ports:
      - "3001:3001"
    environment:
      - NODE_ENV=development
      - CLIENT_URL=http://localhost:3000
    volumes:
      - ./server:/usr/src/app
      - server_node_modules:/usr/src/app/node_modules

  client:
    build:
      context: ./client
      dockerfile: Dockerfile
    ports:
      - "3000:3000"
    environment:
      - REACT_APP_API_URL=http://localhost:3001
      - WDS_SOCKET_PORT=0
    volumes:
      - ./client:/usr/src/app
      - client_node_modules:/usr/src/app/node_modules
    depends_on:
      - server

volumes:
  client_node_modules:
  server_node_modules: