alerts:
- rule: DEPLOYMENT_FAILED
- rule: DOMAIN_FAILED
domains:
- domain: playforward.fedor-ryzhenkov.com
  type: PRIMARY
name: playforward
services:
  - name: frontend
    github:
      repo: fedor-ryzhenkov-main/Playforward
      branch: main
      deploy_on_push: true
    source_dir: client
    environment_slug: node-js
    build_command: npm install && npm run build
    run_command: npm run start
    envs:
      - key: NEXT_PUBLIC_API_URL
        value: https://playforward.fedor-ryzhenkov.com/api

  - name: backend
    github:
      repo: fedor-ryzhenkov-main/Playforward
      branch: main
      deploy_on_push: true
    source_dir: server
    environment_slug: node-js
    build_command: npm install
    run_command: npm start
    envs:
      - key: CLIENT_URL
        value: https://playforward.fedor-ryzhenkov.com