name: playforward
region: lon
ingress:
  rules:
  - component:
      name: playforward-server
    match:
      path:
        prefix: /api
  - component:
      name: playforward-client
    match:
      path:
        prefix: /
domains:
  - domain: playforward.fedor-ryzhenkov.com
    type: PRIMARY
services:
  - name: playforward-server
    github:
      repo: fedor-ryzhenkov-main/Playforward
      branch: main
      deploy_on_push: true
    source_dir: server
    environment_slug: node-js
    build_command: |
      npm install
      apt-get update && apt-get install -y python3-pip ffmpeg && pip3 install yt-dlp
    run_command: npm start
    http_port: 3001
    instance_count: 1
    instance_size_slug: basic-xs
    routes:
      - path: /api
    envs:
      - key: CLIENT_URL
        value: ${APP_URL}
      - key: PORT
        value: "3001"
      - key: NODE_ENV
        value: "production"

static_sites:
  - name: playforward-client
    github:
      repo: fedor-ryzhenkov-main/Playforward
      branch: main
      deploy_on_push: true
    source_dir: client
    build_command: npm install && CI=false npm run build
    output_dir: build
    environment_slug: node-js
    catchall_document: index.html
    routes:
      - path: /
    envs:
      - key: REACT_APP_API_URL
        value: ${APP_URL}/api
      - key: NODE_ENV
        value: "production"